# 自定义规则
## 您可以在此处插入自定义规则
DOMAIN-SUFFIX,tophub.today,DIRECT
DOMAIN-SUFFIX,netmarble.com,Type
DOMAIN-SUFFIX,worldflipper.jp,Type
DOMAIN-SUFFIX,naver.com,Type
DOMAIN-SUFFIX,smartmediarep.com,Type
DOMAIN-SUFFIX,technews.tw,Type


# Google 中国服务
DOMAIN-SUFFIX,services.googleapis.cn,Type
DOMAIN-SUFFIX,xn--ngstr-lra8j.com,Type

# Apple
DOMAIN,developer.apple.com,Type
DOMAIN-SUFFIX,digicert.com,Type
USER-AGENT,com.apple.trustd*,Type
DOMAIN-SUFFIX,apple-dns.net,Type
DOMAIN,testflight.apple.com,Type
DOMAIN,sandbox.itunes.apple.com,Type
DOMAIN,itunes.apple.com,Type
DOMAIN-SUFFIX,apps.apple.com,Type
DOMAIN-SUFFIX,blobstore.apple.com,Type
DOMAIN,cvws.icloud-content.com,Type
DOMAIN,safebrowsing.urlsec.qq.com,DIRECT
DOMAIN,safebrowsing.googleapis.com,DIRECT
USER-AGENT,com.apple.appstored*,DIRECT
USER-AGENT,AppStore*,DIRECT
DOMAIN-SUFFIX,mzstatic.com,DIRECT
DOMAIN-SUFFIX,itunes.apple.com,DIRECT
DOMAIN-SUFFIX,icloud.com,DIRECT
DOMAIN-SUFFIX,icloud-content.com,DIRECT
USER-AGENT,cloudd*,DIRECT
USER-AGENT,*com.apple.WebKit*,DIRECT
USER-AGENT,*com.apple.*,DIRECT
DOMAIN-SUFFIX,me.com,DIRECT
DOMAIN-SUFFIX,aaplimg.com,DIRECT
DOMAIN-SUFFIX,cdn20.com,DIRECT
DOMAIN-SUFFIX,cdn-apple.com,DIRECT
DOMAIN-SUFFIX,akadns.net,DIRECT
DOMAIN-SUFFIX,akamaiedge.net,DIRECT
DOMAIN-SUFFIX,edgekey.net,DIRECT
DOMAIN-SUFFIX,mwcloudcdn.com,DIRECT
DOMAIN-SUFFIX,mwcname.com,DIRECT
DOMAIN-SUFFIX,apple.com,DIRECT
DOMAIN-SUFFIX,apple-cloudkit.com,DIRECT
DOMAIN-SUFFIX,apple-mapkit.com,DIRECT

# 国内网站
USER-AGENT,MicroMessenger Client*,DIRECT
USER-AGENT,WeChat*,DIRECT

DOMAIN-SUFFIX,126.com,DIRECT
DOMAIN-SUFFIX,126.net,DIRECT
DOMAIN-SUFFIX,127.net,DIRECT
DOMAIN-SUFFIX,163.com,DIRECT
DOMAIN-SUFFIX,360buyimg.com,DIRECT
DOMAIN-SUFFIX,36kr.com,DIRECT
DOMAIN-SUFFIX,acfun.tv,DIRECT
DOMAIN-SUFFIX,air-matters.com,DIRECT
DOMAIN-SUFFIX,aixifan.com,DIRECT


DOMAIN-KEYWORD,alicdn,DIRECT
DOMAIN-KEYWORD,alipay,DIRECT
DOMAIN-KEYWORD,aliyun,DIRECT
DOMAIN-KEYWORD,taobao,DIRECT
DOMAIN-SUFFIX,amap.com,DIRECT
DOMAIN-SUFFIX,autonavi.com,DIRECT
DOMAIN-KEYWORD,baidu,DIRECT
DOMAIN-SUFFIX,bdimg.com,DIRECT
DOMAIN-SUFFIX,bdstatic.com,DIRECT
DOMAIN-SUFFIX,bilibili.com,DIRECT
DOMAIN-SUFFIX,bilivideo.com,DIRECT
DOMAIN-SUFFIX,caiyunapp.com,DIRECT
DOMAIN-SUFFIX,clouddn.com,DIRECT
DOMAIN-SUFFIX,cnbeta.com,DIRECT
DOMAIN-SUFFIX,cnbetacdn.com,DIRECT
DOMAIN-SUFFIX,cootekservice.com,DIRECT
DOMAIN-SUFFIX,csdn.net,DIRECT
DOMAIN-SUFFIX,ctrip.com,DIRECT
DOMAIN-SUFFIX,dgtle.com,DIRECT
DOMAIN-SUFFIX,dianping.com,DIRECT
DOMAIN-SUFFIX,douban.com,DIRECT
DOMAIN-SUFFIX,doubanio.com,DIRECT
DOMAIN-SUFFIX,duokan.com,DIRECT
DOMAIN-SUFFIX,easou.com,DIRECT
DOMAIN-SUFFIX,ele.me,DIRECT
DOMAIN-SUFFIX,feng.com,DIRECT
DOMAIN-SUFFIX,fir.im,DIRECT
DOMAIN-SUFFIX,frdic.com,DIRECT
DOMAIN-SUFFIX,g-cores.com,DIRECT
DOMAIN-SUFFIX,godic.net,DIRECT
DOMAIN-SUFFIX,gtimg.com,DIRECT
DOMAIN-SUFFIX,hongxiu.com,DIRECT
DOMAIN-SUFFIX,hxcdn.net,DIRECT
DOMAIN-SUFFIX,iciba.com,DIRECT
DOMAIN-SUFFIX,ifeng.com,DIRECT
DOMAIN-SUFFIX,ifengimg.com,DIRECT
DOMAIN-SUFFIX,ipip.net,DIRECT
DOMAIN-SUFFIX,iqiyi.com,DIRECT
DOMAIN-SUFFIX,jd.com,DIRECT
DOMAIN-SUFFIX,jianshu.com,DIRECT
DOMAIN-SUFFIX,knewone.com,DIRECT
DOMAIN-SUFFIX,le.com,DIRECT
DOMAIN-SUFFIX,lecloud.com,DIRECT
DOMAIN-SUFFIX,lemicp.com,DIRECT
DOMAIN-SUFFIX,licdn.com,DIRECT
DOMAIN-SUFFIX,luoo.net,DIRECT
DOMAIN-SUFFIX,meituan.com,DIRECT
DOMAIN-SUFFIX,meituan.net,DIRECT
DOMAIN-SUFFIX,mi.com,DIRECT
DOMAIN-SUFFIX,miaopai.com,DIRECT
DOMAIN-SUFFIX,microsoft.com,DIRECT
DOMAIN-SUFFIX,microsoftonline.com,DIRECT
DOMAIN-SUFFIX,miui.com,DIRECT
DOMAIN-SUFFIX,miwifi.com,DIRECT
DOMAIN-SUFFIX,mob.com,DIRECT
DOMAIN-SUFFIX,netease.com,DIRECT
DOMAIN-SUFFIX,office.com,DIRECT
DOMAIN-KEYWORD,officecdn,DIRECT
DOMAIN-SUFFIX,office365.com,DIRECT
DOMAIN-SUFFIX,oschina.net,DIRECT
DOMAIN-SUFFIX,ppsimg.com,DIRECT
DOMAIN-SUFFIX,pstatp.com,DIRECT
DOMAIN-SUFFIX,qcloud.com,DIRECT
DOMAIN-SUFFIX,qdaily.com,DIRECT
DOMAIN-SUFFIX,qdmm.com,DIRECT
DOMAIN-SUFFIX,qhimg.com,DIRECT
DOMAIN-SUFFIX,qhres.com,DIRECT
DOMAIN-SUFFIX,qidian.com,DIRECT
DOMAIN-SUFFIX,qihucdn.com,DIRECT
DOMAIN-SUFFIX,qiniu.com,DIRECT
DOMAIN-SUFFIX,qiniucdn.com,DIRECT
DOMAIN-SUFFIX,qiyipic.com,DIRECT
DOMAIN-SUFFIX,qq.com,DIRECT
DOMAIN-SUFFIX,qqurl.com,DIRECT
DOMAIN-SUFFIX,rarbg.to,DIRECT
DOMAIN-SUFFIX,ruguoapp.com,DIRECT
DOMAIN-SUFFIX,segmentfault.com,DIRECT
DOMAIN-SUFFIX,sinaapp.com,DIRECT
DOMAIN-SUFFIX,smzdm.com,DIRECT
DOMAIN-SUFFIX,snapdrop.net,DIRECT
DOMAIN-SUFFIX,sogou.com,DIRECT
DOMAIN-SUFFIX,sogoucdn.com,DIRECT
DOMAIN-SUFFIX,sohu.com,DIRECT
DOMAIN-SUFFIX,soku.com,DIRECT
DOMAIN-SUFFIX,speedtest.net,DIRECT
DOMAIN-SUFFIX,sspai.com,DIRECT
DOMAIN-SUFFIX,suning.com,DIRECT
DOMAIN-SUFFIX,taobao.com,DIRECT
DOMAIN-SUFFIX,tencent.com,DIRECT
DOMAIN-SUFFIX,tenpay.com,DIRECT
DOMAIN-SUFFIX,tianyancha.com,DIRECT
DOMAIN-KEYWORD,.tmall.com,DIRECT
DOMAIN-SUFFIX,tudou.com,DIRECT
DOMAIN-SUFFIX,umetrip.com,DIRECT
DOMAIN-SUFFIX,upaiyun.com,DIRECT
DOMAIN-SUFFIX,upyun.com,DIRECT
DOMAIN-SUFFIX,veryzhun.com,DIRECT
DOMAIN-SUFFIX,weather.com,DIRECT
DOMAIN-SUFFIX,weibo.com,DIRECT
DOMAIN-SUFFIX,xiami.com,DIRECT
DOMAIN-SUFFIX,xiami.net,DIRECT
DOMAIN-SUFFIX,xiaomicp.com,DIRECT
DOMAIN-SUFFIX,ximalaya.com,DIRECT
DOMAIN-SUFFIX,xmcdn.com,DIRECT
DOMAIN-SUFFIX,xunlei.com,DIRECT
DOMAIN-SUFFIX,yhd.com,DIRECT
DOMAIN-SUFFIX,yihaodianimg.com,DIRECT
DOMAIN-SUFFIX,yinxiang.com,DIRECT
DOMAIN-SUFFIX,ykimg.com,DIRECT
DOMAIN-SUFFIX,youdao.com,DIRECT
DOMAIN-SUFFIX,youku.com,DIRECT
DOMAIN-SUFFIX,zealer.com,DIRECT
DOMAIN-SUFFIX,zhihu.com,DIRECT
DOMAIN-SUFFIX,zhimg.com,DIRECT
DOMAIN-SUFFIX,zimuzu.tv,DIRECT
DOMAIN-SUFFIX,zoho.com,DIRECT

# 常见广告
DOMAIN-KEYWORD,admarvel,REJECT-TINYGIF
DOMAIN-KEYWORD,admaster,REJECT-TINYGIF

DOMAIN-KEYWORD,adsage,REJECT-TINYGIF
DOMAIN-KEYWORD,adsmogo,REJECT-TINYGIF
DOMAIN-KEYWORD,adsrvmedia,REJECT-TINYGIF
DOMAIN-KEYWORD,adwords,REJECT-TINYGIF
DOMAIN-KEYWORD,adservice,REJECT-TINYGIF
DOMAIN-SUFFIX,appsflyer.com,REJECT-TINYGIF
DOMAIN-KEYWORD,domob,REJECT-TINYGIF
DOMAIN-SUFFIX,doubleclick.net,REJECT-TINYGIF
DOMAIN-KEYWORD,duomeng,REJECT-TINYGIF
DOMAIN-KEYWORD,dwtrack,REJECT-TINYGIF
DOMAIN-KEYWORD,guanggao,REJECT-TINYGIF
DOMAIN-KEYWORD,lianmeng,REJECT-TINYGIF
DOMAIN-SUFFIX,mmstat.com,REJECT-TINYGIF
DOMAIN-KEYWORD,mopub,REJECT-TINYGIF
DOMAIN-KEYWORD,omgmta,REJECT-TINYGIF
DOMAIN-KEYWORD,openx,REJECT-TINYGIF
DOMAIN-KEYWORD,partnerad,REJECT-TINYGIF
DOMAIN-KEYWORD,pingfore,REJECT-TINYGIF
DOMAIN-KEYWORD,supersonicads,REJECT-TINYGIF
DOMAIN-KEYWORD,uedas,REJECT-TINYGIF
DOMAIN-KEYWORD,umeng,REJECT-TINYGIF
DOMAIN-KEYWORD,usage,REJECT-TINYGIF
DOMAIN-SUFFIX,vungle.com,REJECT-TINYGIF
DOMAIN-KEYWORD,wlmonitor,REJECT-TINYGIF
DOMAIN-KEYWORD,zjtoolbar,REJECT-TINYGIF

## 抗 DNS 污染
DOMAIN-KEYWORD,amazon,Type
DOMAIN-KEYWORD,google,Type
DOMAIN-KEYWORD,gmail,Type
DOMAIN-KEYWORD,youtube,Type
DOMAIN-KEYWORD,facebook,Type
DOMAIN-SUFFIX,fb.me,Type
DOMAIN-SUFFIX,fbcdn.net,Type
DOMAIN-KEYWORD,twitter,Type
DOMAIN-KEYWORD,instagram,Type
DOMAIN-KEYWORD,dropbox,Type
DOMAIN-SUFFIX,twimg.com,Type
DOMAIN-KEYWORD,blogspot,Type
DOMAIN-SUFFIX,youtu.be,Type

## 常见国外域名列表
DOMAIN-SUFFIX,9to5mac.com,Type
DOMAIN-SUFFIX,abpchina.org,Type
DOMAIN-SUFFIX,adblockplus.org,Type
DOMAIN-SUFFIX,adobe.com,Type
DOMAIN-SUFFIX,akamaized.net,Type
DOMAIN-SUFFIX,alfredapp.com,Type
DOMAIN-SUFFIX,amplitude.com,Type
DOMAIN-SUFFIX,ampproject.org,Type
DOMAIN-SUFFIX,android.com,Type
DOMAIN-SUFFIX,angularjs.org,Type
DOMAIN-SUFFIX,aolcdn.com,Type
DOMAIN-SUFFIX,apkpure.com,Type
DOMAIN-SUFFIX,appledaily.com,Type
DOMAIN-SUFFIX,appshopper.com,Type
DOMAIN-SUFFIX,appspot.com,Type
DOMAIN-SUFFIX,arcgis.com,Type
DOMAIN-SUFFIX,archive.org,Type
DOMAIN-SUFFIX,armorgames.com,Type
DOMAIN-SUFFIX,aspnetcdn.com,Type
DOMAIN-SUFFIX,att.com,Type
DOMAIN-SUFFIX,awsstatic.com,Type
DOMAIN-SUFFIX,azureedge.net,Type
DOMAIN-SUFFIX,azurewebsites.net,Type
DOMAIN-SUFFIX,bing.com,Type
DOMAIN-SUFFIX,bintray.com,Type
DOMAIN-SUFFIX,bit.com,Type
DOMAIN-SUFFIX,bit.ly,Type
DOMAIN-SUFFIX,bitbucket.org,Type
DOMAIN-SUFFIX,bjango.com,Type
DOMAIN-SUFFIX,bkrtx.com,Type
DOMAIN-SUFFIX,blog.com,Type
DOMAIN-SUFFIX,blogcdn.com,Type
DOMAIN-SUFFIX,blogger.com,Type
DOMAIN-SUFFIX,blogsmithmedia.com,Type
DOMAIN-SUFFIX,blogspot.com,Type
DOMAIN-SUFFIX,blogspot.hk,Type
DOMAIN-SUFFIX,bloomberg.com,Type
DOMAIN-SUFFIX,box.com,Type
DOMAIN-SUFFIX,box.net,Type
DOMAIN-SUFFIX,cachefly.net,Type
DOMAIN-SUFFIX,chromium.org,Type
DOMAIN-SUFFIX,cl.ly,Type
DOMAIN-SUFFIX,cloudflare.com,Type
DOMAIN-SUFFIX,cloudfront.net,Type
DOMAIN-SUFFIX,cloudmagic.com,Type
DOMAIN-SUFFIX,cmail19.com,Type
DOMAIN-SUFFIX,cnet.com,Type
DOMAIN-SUFFIX,cocoapods.org,Type
DOMAIN-SUFFIX,comodoca.com,Type
DOMAIN-SUFFIX,crashlytics.com,Type
DOMAIN-SUFFIX,culturedcode.com,Type
DOMAIN-SUFFIX,d.pr,Type
DOMAIN-SUFFIX,danilo.to,Type
DOMAIN-SUFFIX,dayone.me,Type
DOMAIN-SUFFIX,db.tt,Type
DOMAIN-SUFFIX,deskconnect.com,Type
DOMAIN-SUFFIX,disq.us,Type
DOMAIN-SUFFIX,disqus.com,Type
DOMAIN-SUFFIX,disquscdn.com,Type
DOMAIN-SUFFIX,dnsimple.com,Type
DOMAIN-SUFFIX,docker.com,Type
DOMAIN-SUFFIX,dribbble.com,Type
DOMAIN-SUFFIX,droplr.com,Type
DOMAIN-SUFFIX,duckduckgo.com,Type
DOMAIN-SUFFIX,dueapp.com,Type
DOMAIN-SUFFIX,dytt8.net,Type
DOMAIN-SUFFIX,edgecastcdn.net,Type
DOMAIN-SUFFIX,edgekey.net,Type
DOMAIN-SUFFIX,edgesuite.net,Type
DOMAIN-SUFFIX,engadget.com,Type
DOMAIN-SUFFIX,entrust.net,Type
DOMAIN-SUFFIX,eurekavpt.com,Type
DOMAIN-SUFFIX,evernote.com,Type
DOMAIN-SUFFIX,fabric.io,Type
DOMAIN-SUFFIX,fast.com,Type
DOMAIN-SUFFIX,fastly.net,Type

DOMAIN-SUFFIX,fc2.com,Type
DOMAIN-SUFFIX,feedburner.com,Type
DOMAIN-SUFFIX,feedly.com,Type
DOMAIN-SUFFIX,feedsportal.com,Type
DOMAIN-SUFFIX,fiftythree.com,Type
DOMAIN-SUFFIX,firebaseio.com,Type
DOMAIN-SUFFIX,flexibits.com,Type
DOMAIN-SUFFIX,flickr.com,Type
DOMAIN-SUFFIX,flipboard.com,Type
DOMAIN-SUFFIX,g.co,Type
DOMAIN-SUFFIX,gabia.net,Type
DOMAIN-SUFFIX,geni.us,Type
DOMAIN-SUFFIX,gfx.ms,Type
DOMAIN-SUFFIX,ggpht.com,Type
DOMAIN-SUFFIX,ghostnoteapp.com,Type
DOMAIN-SUFFIX,git.io,Type
DOMAIN-KEYWORD,github,Type
DOMAIN-SUFFIX,globalsign.com,Type
DOMAIN-SUFFIX,gmodules.com,Type
DOMAIN-SUFFIX,godaddy.com,Type
DOMAIN-SUFFIX,golang.org,Type
DOMAIN-SUFFIX,gongm.in,Type
DOMAIN-SUFFIX,goo.gl,Type
DOMAIN-SUFFIX,goodreaders.com,Type
DOMAIN-SUFFIX,goodreads.com,Type
DOMAIN-SUFFIX,gravatar.com,Type
DOMAIN-SUFFIX,gstatic.com,Type
DOMAIN-SUFFIX,gvt0.com,Type
DOMAIN-SUFFIX,hockeyapp.net,Type
DOMAIN-SUFFIX,hotmail.com,Type
DOMAIN-SUFFIX,icons8.com,Type
DOMAIN-SUFFIX,ifixit.com,Type
DOMAIN-SUFFIX,ift.tt,Type
DOMAIN-SUFFIX,ifttt.com,Type
DOMAIN-SUFFIX,iherb.com,Type
DOMAIN-SUFFIX,imageshack.us,Type
DOMAIN-SUFFIX,img.ly,Type
DOMAIN-SUFFIX,imgur.com,Type
DOMAIN-SUFFIX,imore.com,Type
DOMAIN-SUFFIX,instapaper.com,Type
DOMAIN-SUFFIX,ipn.li,Type
DOMAIN-SUFFIX,is.gd,Type
DOMAIN-SUFFIX,issuu.com,Type
DOMAIN-SUFFIX,itgonglun.com,Type
DOMAIN-SUFFIX,itun.es,Type
DOMAIN-SUFFIX,ixquick.com,Type
DOMAIN-SUFFIX,j.mp,Type
DOMAIN-SUFFIX,js.revsci.net,Type
DOMAIN-SUFFIX,jshint.com,Type
DOMAIN-SUFFIX,jtvnw.net,Type
DOMAIN-SUFFIX,justgetflux.com,Type
DOMAIN-SUFFIX,kat.cr,Type
DOMAIN-SUFFIX,klip.me,Type
DOMAIN-SUFFIX,libsyn.com,Type
DOMAIN-SUFFIX,linkedin.com,Type
DOMAIN-SUFFIX,line-apps.com,Type
DOMAIN-SUFFIX,linode.com,Type
DOMAIN-SUFFIX,lithium.com,Type
DOMAIN-SUFFIX,littlehj.com,Type
DOMAIN-SUFFIX,live.com,Type
DOMAIN-SUFFIX,live.net,Type
DOMAIN-SUFFIX,livefilestore.com,Type
DOMAIN-SUFFIX,llnwd.net,Type
DOMAIN-SUFFIX,macid.co,Type
DOMAIN-SUFFIX,macromedia.com,Type
DOMAIN-SUFFIX,macrumors.com,Type
DOMAIN-SUFFIX,mashable.com,Type
DOMAIN-SUFFIX,mathjax.org,Type
DOMAIN-SUFFIX,medium.com,Type
DOMAIN-SUFFIX,mega.co.nz,Type
DOMAIN-SUFFIX,mega.nz,Type
DOMAIN-SUFFIX,megaupload.com,Type
DOMAIN-SUFFIX,microsofttranslator.com,Type
DOMAIN-SUFFIX,mindnode.com,Type
DOMAIN-SUFFIX,mobile01.com,Type
DOMAIN-SUFFIX,modmyi.com,Type
DOMAIN-SUFFIX,msedge.net,Type
DOMAIN-SUFFIX,myfontastic.com,Type
DOMAIN-SUFFIX,name.com,Type
DOMAIN-SUFFIX,nextmedia.com,Type
DOMAIN-SUFFIX,nsstatic.net,Type
DOMAIN-SUFFIX,nssurge.com,Type
DOMAIN-SUFFIX,nyt.com,Type
DOMAIN-SUFFIX,nytimes.com,Type
DOMAIN-SUFFIX,omnigroup.com,Type
DOMAIN-SUFFIX,onedrive.com,Type
DOMAIN-SUFFIX,onenote.com,Type
DOMAIN-SUFFIX,ooyala.com,Type
DOMAIN-SUFFIX,openvpn.net,Type
DOMAIN-SUFFIX,openwrt.org,Type
DOMAIN-SUFFIX,orkut.com,Type
DOMAIN-SUFFIX,osxdaily.com,Type
DOMAIN-SUFFIX,outlook.com,Type
DOMAIN-SUFFIX,ow.ly,Type
DOMAIN-SUFFIX,paddleapi.com,Type
DOMAIN-SUFFIX,parallels.com,Type
DOMAIN-SUFFIX,parse.com,Type
DOMAIN-SUFFIX,pdfexpert.com,Type
DOMAIN-SUFFIX,periscope.tv,Type
DOMAIN-SUFFIX,pinboard.in,Type
DOMAIN-SUFFIX,pinterest.com,Type
DOMAIN-SUFFIX,pixelmator.com,Type
DOMAIN-SUFFIX,pixiv.net,Type
DOMAIN-SUFFIX,playpcesor.com,Type
DOMAIN-SUFFIX,playstation.com,Type
DOMAIN-SUFFIX,playstation.com.hk,Type
DOMAIN-SUFFIX,playstation.net,Type
DOMAIN-SUFFIX,playstationnetwork.com,Type
DOMAIN-SUFFIX,pushwoosh.com,Type
DOMAIN-SUFFIX,rime.im,Type
DOMAIN-SUFFIX,servebom.com,Type
DOMAIN-SUFFIX,sfx.ms,Type
DOMAIN-SUFFIX,shadowsocks.org,Type
DOMAIN-SUFFIX,sharethis.com,Type
DOMAIN-SUFFIX,shazam.com,Type
DOMAIN-SUFFIX,skype.com,Type
DOMAIN-SUFFIX,smartdnsProxy.com,Type
DOMAIN-SUFFIX,smartmailcloud.com,Type
DOMAIN-SUFFIX,sndcdn.com,Type


DOMAIN-SUFFIX,sony.com,Type
DOMAIN-SUFFIX,soundcloud.com,Type
DOMAIN-SUFFIX,sourceforge.net,Type
DOMAIN-SUFFIX,spotify.com,Type
DOMAIN-SUFFIX,squarespace.com,Type
DOMAIN-SUFFIX,sstatic.net,Type
DOMAIN-SUFFIX,st.luluku.pw,Type
DOMAIN-SUFFIX,stackoverflow.com,Type
DOMAIN-SUFFIX,startpage.com,Type
DOMAIN-SUFFIX,staticflickr.com,Type
DOMAIN-SUFFIX,steamcommunity.com,Type
DOMAIN-SUFFIX,symauth.com,Type
DOMAIN-SUFFIX,symcb.com,Type
DOMAIN-SUFFIX,symcd.com,Type
DOMAIN-SUFFIX,tapbots.com,Type
DOMAIN-SUFFIX,tapbots.net,Type
DOMAIN-SUFFIX,tdesktop.com,Type
DOMAIN-SUFFIX,techcrunch.com,Type
DOMAIN-SUFFIX,techsmith.com,Type
DOMAIN-SUFFIX,thepiratebay.org,Type
DOMAIN-SUFFIX,theverge.com,Type
DOMAIN-SUFFIX,time.com,Type
DOMAIN-SUFFIX,timeinc.net,Type
DOMAIN-SUFFIX,tiny.cc,Type
DOMAIN-SUFFIX,tinypic.com,Type
DOMAIN-SUFFIX,tmblr.co,Type
DOMAIN-SUFFIX,todoist.com,Type
DOMAIN-SUFFIX,trello.com,Type
DOMAIN-SUFFIX,trustasiassl.com,Type
DOMAIN-SUFFIX,tumblr.co,Type
DOMAIN-SUFFIX,tumblr.com,Type
DOMAIN-SUFFIX,tweetdeck.com,Type
DOMAIN-SUFFIX,tweetmarker.net,Type
DOMAIN-SUFFIX,twitch.tv,Type
DOMAIN-SUFFIX,txmblr.com,Type
DOMAIN-SUFFIX,typekit.net,Type
DOMAIN-SUFFIX,ubertags.com,Type
DOMAIN-SUFFIX,ublock.org,Type
DOMAIN-SUFFIX,ubnt.com,Type
DOMAIN-SUFFIX,ulyssesapp.com,Type
DOMAIN-SUFFIX,urchin.com,Type
DOMAIN-SUFFIX,usertrust.com,Type
DOMAIN-SUFFIX,v.gd,Type
DOMAIN-SUFFIX,v2ex.com,Type
DOMAIN-SUFFIX,vimeo.com,Type
DOMAIN-SUFFIX,vimeocdn.com,Type
DOMAIN-SUFFIX,vine.co,Type
DOMAIN-SUFFIX,vivaldi.com,Type
DOMAIN-SUFFIX,vox-cdn.com,Type
DOMAIN-SUFFIX,vsco.co,Type
DOMAIN-SUFFIX,vultr.com,Type
DOMAIN-SUFFIX,w.org,Type
DOMAIN-SUFFIX,w3schools.com,Type
DOMAIN-SUFFIX,webtype.com,Type
DOMAIN-SUFFIX,wikiwand.com,Type
DOMAIN-SUFFIX,wikileaks.org,Type
DOMAIN-SUFFIX,wikimedia.org,Type
DOMAIN-SUFFIX,wikipedia.com,Type
DOMAIN-SUFFIX,wikipedia.org,Type
DOMAIN-SUFFIX,windows.com,Type
DOMAIN-SUFFIX,windows.net,Type
DOMAIN-SUFFIX,wire.com,Type
DOMAIN-SUFFIX,wordpress.com,Type
DOMAIN-SUFFIX,workflowy.com,Type
DOMAIN-SUFFIX,wp.com,Type
DOMAIN-SUFFIX,wsj.com,Type
DOMAIN-SUFFIX,wsj.net,Type
DOMAIN-SUFFIX,xda-developers.com,Type
DOMAIN-SUFFIX,xeeno.com,Type
DOMAIN-SUFFIX,xiti.com,Type
DOMAIN-SUFFIX,yahoo.com,Type
DOMAIN-SUFFIX,yimg.com,Type
DOMAIN-SUFFIX,ying.com,Type
DOMAIN-SUFFIX,yoyo.org,Type
DOMAIN-SUFFIX,ytimg.com,Type

# Telegram
DOMAIN-SUFFIX,telegra.ph,Type
DOMAIN-SUFFIX,telegram.org,Type

IP-CIDR,91.108.4.0/22,Type,no-resolve
IP-CIDR,91.108.8.0/21,Type,no-resolve
IP-CIDR,91.108.16.0/22,Type,no-resolve
IP-CIDR,91.108.56.0/22,Type,no-resolve
IP-CIDR,149.154.160.0/20,Type,no-resolve
IP-CIDR6,2001:67c:4e8::/48,Type,no-resolve
IP-CIDR6,2001:b28:f23d::/48,Type,no-resolve
IP-CIDR6,2001:b28:f23f::/48,Type,no-resolve

# Google 中国服务 services.googleapis.cn
IP-CIDR,120.232.181.162/32,Type,no-resolve
IP-CIDR,120.241.147.226/32,Type,no-resolve
IP-CIDR,120.253.253.226/32,Type,no-resolve
IP-CIDR,120.253.255.162/32,Type,no-resolve
IP-CIDR,120.253.255.34/32,Type,no-resolve
IP-CIDR,120.253.255.98/32,Type,no-resolve
IP-CIDR,180.163.150.162/32,Type,no-resolve
IP-CIDR,180.163.150.34/32,Type,no-resolve
IP-CIDR,180.163.151.162/32,Type,no-resolve
IP-CIDR,180.163.151.34/32,Type,no-resolve
IP-CIDR,203.208.39.0/24,Type,no-resolve
IP-CIDR,203.208.40.0/24,Type,no-resolve
IP-CIDR,203.208.41.0/24,Type,no-resolve
IP-CIDR,203.208.43.0/24,Type,no-resolve
IP-CIDR,203.208.50.0/24,Type,no-resolve
IP-CIDR,220.181.174.162/32,Type,no-resolve
IP-CIDR,220.181.174.226/32,Type,no-resolve
IP-CIDR,220.181.174.34/32,Type,no-resolve

# LAN
DOMAIN-SUFFIX,local,DIRECT
IP-CIDR,127.0.0.0/8,DIRECT
IP-CIDR,172.16.0.0/12,DIRECT
IP-CIDR,192.168.0.0/16,DIRECT
IP-CIDR,10.0.0.0/8,DIRECT
IP-CIDR,17.0.0.0/8,DIRECT
IP-CIDR,100.64.0.0/10,DIRECT
IP-CIDR,224.0.0.0/4,DIRECT
IP-CIDR6,fe80::/10,DIRECT

# 剩余未匹配的国内网站
DOMAIN-SUFFIX,cn,DIRECT
DOMAIN-KEYWORD,-cn,DIRECT

# 最终规则
GEOIP,CN,DIRECT
FINAL,Type